"""initial relational schema

Revision ID: 6a0e1ab23641
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "6a0e1ab23641"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "creators",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "form_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("form_id", sa.String(length=36), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("source_draft_revision", sa.Integer(), nullable=False),
        sa.Column("definition_json", sa.JSON(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("version_number > 0", name="ck_version_number"),
        sa.ForeignKeyConstraint(["form_id"], ["forms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("form_id", "id", name="uq_form_version_owner"),
        sa.UniqueConstraint("form_id", "version_number", name="uq_form_version_number"),
    )
    with op.batch_alter_table("form_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_form_versions_form_id"), ["form_id"], unique=False)

    op.create_table(
        "forms",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("creator_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("draft_revision", sa.Integer(), nullable=False),
        sa.Column("published_version_id", sa.String(length=36), nullable=True),
        sa.Column("theme_json", sa.JSON(), nullable=False),
        sa.Column("thank_you_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status != 'published' OR published_version_id IS NOT NULL",
            name="ck_published_has_version",
        ),
        sa.CheckConstraint("status IN ('draft', 'published')", name="ck_form_status"),
        sa.CheckConstraint("draft_revision >= 0", name="ck_form_revision"),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["creators.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id", "published_version_id"],
            ["form_versions.form_id", "form_versions.id"],
            name="fk_form_published_version_owner",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    with op.batch_alter_table("forms", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_forms_creator_id"), ["creator_id"], unique=False)

    op.create_table(
        "questions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("form_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("settings_json", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "type IN ('short_text', 'long_text', 'multiple_choice', 'dropdown', "
            "'email', 'number', 'yes_no', 'rating')",
            name="ck_question_type",
        ),
        sa.ForeignKeyConstraint(["form_id"], ["forms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("form_id", "position", name="uq_question_position"),
    )
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_questions_form_id"), ["form_id"], unique=False)

    op.create_table(
        "submissions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("form_id", sa.String(length=36), nullable=False),
        sa.Column("form_version_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=36), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_id", "form_version_id"],
            ["form_versions.form_id", "form_versions.id"],
            name="fk_submission_version_owner",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["form_id"], ["forms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("form_id", "idempotency_key", name="uq_submission_attempt"),
    )
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_submissions_form_id"), ["form_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_submissions_form_version_id"), ["form_version_id"], unique=False
        )

    op.create_table(
        "answers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("question_key", sa.String(length=36), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("submission_id", "question_key", name="uq_answer_question"),
    )
    with op.batch_alter_table("answers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_answers_submission_id"), ["submission_id"], unique=False
        )

    op.create_table(
        "question_options",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("question_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("question_id", "position", name="uq_option_position"),
    )
    with op.batch_alter_table("question_options", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_options_question_id"), ["question_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # Break the published-pointer cycle before cascading owned definitions.
    op.execute("UPDATE forms SET status = 'draft', published_version_id = NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_options", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_options_question_id"))

    op.drop_table("question_options")
    with op.batch_alter_table("answers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_answers_submission_id"))

    op.drop_table("answers")
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_submissions_form_version_id"))
        batch_op.drop_index(batch_op.f("ix_submissions_form_id"))

    op.drop_table("submissions")
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_questions_form_id"))

    op.drop_table("questions")
    with op.batch_alter_table("forms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forms_creator_id"))

    op.drop_table("forms")
    with op.batch_alter_table("form_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_form_versions_form_id"))

    op.drop_table("form_versions")
    op.drop_table("creators")
    # ### end Alembic commands ###
